version: '3'
services:

  projectmanagermysqldb:
    image: mysql:8
    networks:
      - projectmanager-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
      - MYSQL_DATABASE=pmsdb 

  projectmanager-service:
    image: projectmanagerapi
    ports:
      - "8095:8095"
    networks:
      - projectmanager-mysql
    depends_on:
      - projectmanagermysqldb
      
  projectmanagerui:
    image: projectmanagerui
    ports:
      - "4200:4200"
    networks:
      - projectmanager-mysql
    depends_on:
      - projectmanager-service


networks:
  projectmanager-mysql: